### ISSUE TITLE
New naming convention

### ISSUE THREAD

**Issue by meggart** [CAB-LAB/CABLAB.jl#1]
@forman I restructured the Julia package and implemented the new naming convention that you suggested. I also reorganized the files so that the folder structure reflects the top hierarchy of the module structure, too. The user now has the choice to do either

```
using CABLAB
```

to import all the exported names from all sub-modules. A second possibility is to call

```
import CABLAB
using CABLAB.CubeAPI, CABLAB.Proc
```

if the user only wants to import names from the CubeAPI and the Proc submodule. A fully specified acces is possible, too:

```
import CABLAB
cube = CABLAB.CubeAPI.Cube("pathtoCube")
cubedata = CABLAB.CubeAPI.getCubeData(cube,....)
scores     = CABLAB.Proc.scores(cubedata)
```

Are you ok with this structure?

**Comment by forman** [comment]
Better now. However, I'd prefer to avoid 'API' in package names as all public packages are API by design. Why don't you just skip 'CubeAPI' and add its components to CABLAB?

**Comment by forman** [comment]
Btw, can we pls also have

    cubedata = cube.getCubeData(....)

instead of the verbose

    cubedata = CABLAB.CubeAPI.getCubeData(cube,....)

**Comment by meggart** [comment]
Ok, will move everything in CubeAPI to the CABLAB namespace.

The verbose version `CABLAB.CubeAPI.getCubeData` is just shown for demonstration. The name is automatically imported when you only write `using CABLAB` which is what the standard user would do.

**Comment by forman** [comment]
So, Julia can't use the object notation?

**Comment by meggart** [comment]
Yes, one could emulate it by overwriting the getfield operator, but it is discouraged.
