### ISSUE TITLE
maskAllNan

### ISSUE THREAD

**Issue by gdkrmr** [CAB-LAB/CABLAB.jl#10]
Situation:

fillMSC -> removeMSC -> sampleLandPoints -> some points are still nan, because a complete timeseries was missing.

proposed solution:
1) add argument to fillMSC to mask out timeseries that could not be fille
2) add a function like maskAllNan which masks out everything that contains nans

**Comment by gdkrmr** [comment]
allso something like

setMask!(Cube, value, index...)

would be useful

**Comment by meggart** [comment]
the function `sampleLandPoints` has a nomissing argument now, this means that it only samples points where not a single missing value is present in any variable.
