### ISSUE TITLE
saveCube() error

### ISSUE THREAD

**Issue by milanflach** [CAB-LAB/CABLAB.jl#57]
save cube is only working, in the case when the filename is in the directory of the current path
save, because mkdir() allows in julia 0.6 not for creating subdirectories. 
works: saveCube(cdata_filled, "test")
works not: saveCube(cdata_filled, "test/test")

Is it possible to change
mkdir() --> mkpath(), e.g. in Cubes.jl l. 190
I assume it would fix the problem ...

**Comment by meggart** [comment]
Ok, will change this in the next version
