### ISSUE TITLE
@loadOrGeneate error

### ISSUE THREAD

**Issue by milanflach** [CAB-LAB/CABLAB.jl#58]
the nice @loadOrGenerate macro does not recognise the strings anymore... to strict checking?
@loadOrGenerate cdata_filled => "test" begin 
    cdata_filled = mapCube(gapFillMSC, cdata)
end

Give error: "Wrong Argument type", although being from the examples ...

**Comment by meggart** [comment]
I already fixed this with @mafla and it will be corrected in the new version i plan to push by the end of the week.
